# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration) ./backend/ClimateComparison.sln
  displayName: 'dotnet build'

- script: dotnet publish --output $(Build.ArtifactStagingDirectory)/backend ./backend/ClimateComparison.sln
  displayName: 'dotnet publish'

- publish: $(Build.ArtifactStagingDirectory)/backend
  artifact: backend
  displayName: 'publish backend'

- script: npm install
  workingDirectory: frontend
  displayName: 'npm install'
  
- script: npm run build
  workingDirectory: frontend
  displayName: 'npm build'

- publish: frontend/build
  artifact: frontend
  displayName: 'publish frontend'