CREATE TABLE Cities(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	Name NVARCHAR(200) NOT NULL,
	AltNames NVARCHAR(MAX) NOT NULL,
	Location GEOGRAPHY NOT NULL,
	CountryCode CHAR(2) NOT NULL,
	Population INT NOT NULL
)