name: Build and Deploy
on: 
  push: 
    branches: 
      - main
      - feature/*
      - github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      buildConfiguration: 'Release'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '2.1.x'
      - name: 'dotnet build'
        run: dotnet build --configuration $buildConfiguration ./backend/ClimateComparison.sln
  