name: Build and Deploy
on: 
  push: 
    branches: 
      - main
      - feature/*
      - github_actions

jobs:
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    env:
      buildConfiguration: 'Release'
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '2.1.x'
      - name: 'dotnet build'
        run: dotnet build --configuration $buildConfiguration 
      - name: 'dotnet publish'
        run: dotnet publish --output ${{ github.workspace }}/backend_output 
      - name: Upload backend
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: ${{ github.workspace }}/backend_output


  